import type { University, Certificate } from './types';

export const UNIVERSITIES: University[] = [
  { id: 'u1', name: 'University of Khartoum', country: 'Sudan' },
  { id: 'u2', name: 'Sudan University of Science and Technology', country: 'Sudan' },
  { id: 'u3', name: 'Al-Neelain University', country: 'Sudan' },
];

export const CERTIFICATES: Certificate[] = [
  {
    id: 'CS-UOFK-2023-001',
    studentName: 'Ahmed Al-Nil',
    universityId: 'u1',
    degree: 'Bachelor of Science',
    major: 'Computer Science',
    graduationDate: '2023-05-15',
    issueDate: '2023-05-20',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CS-UOFK-2023-001',
  },
  {
    id: 'EE-SUST-2022-045',
    studentName: 'Fatima Omar',
    universityId: 'u2',
    degree: 'Bachelor of Engineering',
    major: 'Electrical Engineering',
    graduationDate: '2022-06-01',
    issueDate: '2022-06-10',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=EE-SUST-2022-045',
  },
  {
    id: 'BA-NU-2023-102',
    studentName: 'Mohammed Osman',
    universityId: 'u3',
    degree: 'Master of Business Administration',
    major: 'Finance',
    graduationDate: '2023-08-20',
    issueDate: '2023-08-25',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BA-NU-2023-102',
  },
];

export const TRANSLATIONS = {
  en: {
    // Header
    appName: "CertiVerify",
    home: "Home",
    verify: "Verify Certificate",
    admin: "Admin",
    logout: "Logout",
    logoutConfirmation: "Are you sure you want to log out?",

    // Home Page
    heroTitle: "Secure & Instant Certificate Verification",
    heroSubtitle: "A trusted platform for universities and employers to verify academic credentials with confidence.",
    heroButton: "Verify a Certificate Now",
    howItWorks: "How It Works",
    feature1Title: "Enter ID",
    feature1Desc: "Simply enter the unique certificate ID found on the document.",
    feature2Title: "Instant Verification",
    feature2Desc: "Our system instantly checks the database for a valid record.",
    feature3Title: "View & Confirm",
    feature3Desc: "Receive immediate confirmation of the certificate's authenticity and details.",

    // Verification Page
    verifyTitle: "Verify Certificate",
    verifySubtitle: "Enter the certificate ID to check its validity.",
    placeholder: "Enter Certificate ID...",
    verifyButton: "Verify",
    verifyingButton: "Verifying...",
    errorRequired: "Certificate ID is required.",
    invalidQrCodeError: "Invalid or unrecognized Certificate ID.",
    scanQrCode: "Scan with Camera",
    uploadQrCode: "Upload Image",
    or: "OR",
    stopScanning: "Cancel Scan",
    scannerInstruction: "Point your camera at the QR code.",
    qrScanError: "No QR code could be found in the uploaded image. Please try another image.",


    // Certificate Details Page
    verifiedTitle: "Certificate Verified",
    verifiedSubtitle: "This is a valid certificate issued by {universityName}.",
    failedTitle: "Verification Failed",
    failedSubtitle: "The certificate ID could not be found. Please check the ID and try again.",
    studentName: "Student Name",
    issuingUniversity: "Issuing University",
    degree: "Degree",
    major: "Major",
    graduationDate: "Graduation Date",
    certificateId: "Certificate ID",
    disclaimer: "This document was verified on {date}. This is an official record from the issuing institution, {universityName}.",
    verifyAnotherButton: "Verify Another Certificate",
    downloadPdfButton: "Download as PDF",
    downloadingPdfButton: "Downloading...",
    
    // Admin Login Page
    adminLoginTitle: "Admin Portal",
    adminLoginSubtitle: "Please sign in to continue.",
    usernameLabel: "Username",
    usernamePlaceholder: "admin",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    signInButton: "Sign In",
    invalidCredentialsError: "Invalid username or password.",

    // Admin Dashboard Page
    dashboardTitle: "Admin Dashboard",
    welcomeMessage: "Welcome, {name}",
    totalCerts: "Total Certificates",
    totalUnis: "Total Universities",
    totalVerifications: "Total Verifications",
    verificationLogs: "Verification Logs",
    logId: "Log ID",
    certId: "Certificate ID",
    timestamp: "Timestamp",
    status: "Status",
    ipAddress: "IP Address",
    statusSuccess: "Success",
    statusFailed: "Failed",
    // Certificate Management
    manageCertificates: "Manage Certificates",
    addNewCertificate: "Add New Certificate",
    editCertificate: "Edit Certificate",
    deleteCertificate: "Delete Certificate",
    deleteConfirmation: "Are you sure you want to delete this certificate? This action cannot be undone.",
    actions: "Actions",
    university: "University",
    save: "Save",
    cancel: "Cancel",
    studentNamePlaceholder: "e.g., Omar Al-Fahad",
    degreePlaceholder: "e.g., Bachelor of Science",
    majorPlaceholder: "e.g., Computer Science",
    graduationDateLabel: "Graduation Date",
    // University Management
    manageUniversities: "Manage Universities",
    addNewUniversity: "Add New University",
    editUniversity: "Edit University",
    deleteUniversity: "Delete University",
    deleteUniversityConfirmation: "Are you sure you want to delete this university? This action cannot be undone.",
    universityId: "University ID",
    universityName: "University Name",
    country: "Country",
    universityNamePlaceholder: "e.g., King Saud University",
    countryPlaceholder: "e.g., Saudi Arabia",
  },
  ar: {
    // Header
    appName: "التحقق من الشهادات",
    home: "الرئيسية",
    verify: "تحقق من شهادة",
    admin: "مسؤول",
    logout: "تسجيل الخروج",
    logoutConfirmation: "هل أنت متأكد أنك تريد تسجيل الخروج؟",

    // Home Page
    heroTitle: "تحقق آمن وفوري من الشهادات",
    heroSubtitle: "منصة موثوقة للجامعات وأصحاب العمل للتحقق من المؤهلات الأكاديمية بثقة.",
    heroButton: "تحقق من شهادة الآن",
    howItWorks: "كيف يعمل",
    feature1Title: "أدخل المعرف",
    feature1Desc: "ما عليك سوى إدخال معرف الشهادة الفريد الموجود في المستند.",
    feature2Title: "تحقق فوري",
    feature2Desc: "يقوم نظامنا على الفور بالتحقق من قاعدة البيانات بحثًا عن سجل صالح.",
    feature3Title: "عرض وتأكيد",
    feature3Desc: "احصل على تأكيد فوري لصحة الشهادة وتفاصيلها.",
    
    // Verification Page
    verifyTitle: "التحقق من الشهادة",
    verifySubtitle: "أدخل معرف الشهادة للتحقق من صلاحيتها.",
    placeholder: "أدخل معرف الشهادة...",
    verifyButton: "تحقق",
    verifyingButton: "يتم التحقق...",
    errorRequired: "معرف الشهادة مطلوب.",
    invalidQrCodeError: "معرف شهادة غير صالح أو غير معترف به.",
    scanQrCode: "المسح بالكاميرا",
    uploadQrCode: "رفع صورة",
    or: "أو",
    stopScanning: "إلغاء المسح",
    scannerInstruction: "وجه الكاميرا نحو رمز الاستجابة السريعة.",
    qrScanError: "تعذر العثور على رمز الاستجابة السريعة في الصورة المرفوعة. يرجى تجربة صورة أخرى.",

    // Certificate Details Page
    verifiedTitle: "تم التحقق من الشهادة",
    verifiedSubtitle: "هذه شهادة صالحة صادرة عن {universityName}.",
    failedTitle: "فشل التحقق",
    failedSubtitle: "تعذر العثور على معرف الشهادة. يرجى التحقق من المعرف والمحاولة مرة أخرى.",
    studentName: "اسم الطالب",
    issuingUniversity: "الجامعة المصدرة",
    degree: "الدرجة العلمية",
    major: "التخصص",
    graduationDate: "تاريخ التخرج",
    certificateId: "معرف الشهادة",
    disclaimer: "تم التحقق من هذا المستند في {date}. هذا سجل رسمي من المؤسسة المصدرة، {universityName}.",
    verifyAnotherButton: "تحقق من شهادة أخرى",
    downloadPdfButton: "تنزيل كملف PDF",
    downloadingPdfButton: "جاري التنزيل...",
    
    // Admin Login Page
    adminLoginTitle: "بوابة المسؤول",
    adminLoginSubtitle: "يرجى تسجيل الدخول للمتابعة.",
    usernameLabel: "اسم المستخدم",
    usernamePlaceholder: "admin",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "••••••••",
    signInButton: "تسجيل الدخول",
    invalidCredentialsError: "اسم المستخدم أو كلمة المرور غير صالحة.",

    // Admin Dashboard Page
    dashboardTitle: "لوحة تحكم المسؤول",
    welcomeMessage: "مرحباً بك، {name}",
    totalCerts: "إجمالي الشهادات",
    totalUnis: "إجمالي الجامعات",
    totalVerifications: "إجمالي عمليات التحقق",
    verificationLogs: "سجلات التحقق",
    logId: "معرف السجل",
    certId: "معرف الشهادة",
    timestamp: "التوقيت",
    status: "الحالة",
    ipAddress: "عنوان IP",
    statusSuccess: "نجاح",
    statusFailed: "فشل",
    // Certificate Management
    manageCertificates: "إدارة الشهادات",
    addNewCertificate: "إضافة شهادة جديدة",
    editCertificate: "تعديل الشهادة",
    deleteCertificate: "حذف الشهادة",
    deleteConfirmation: "هل أنت متأكد أنك تريد حذف هذه الشهادة؟ لا يمكن التراجع عن هذا الإجراء.",
    actions: "الإجراءات",
    university: "الجامعة",
    save: "حفظ",
    cancel: "إلغاء",
    studentNamePlaceholder: "مثال: عمر الفهد",
    degreePlaceholder: "مثال: بكالوريوس العلوم",
    majorPlaceholder: "مثال: علوم الحاسب",
    graduationDateLabel: "تاريخ التخرج",
    // University Management
    manageUniversities: "إدارة الجامعات",
    addNewUniversity: "إضافة جامعة جديدة",
    editUniversity: "تعديل الجامعة",
    deleteUniversity: "حذف الجامعة",
    deleteUniversityConfirmation: "هل أنت متأكد أنك تريد حذف هذه الجامعة؟ لا يمكن التراجع عن هذا الإجراء.",
    universityId: "معرف الجامعة",
    universityName: "اسم الجامعة",
    country: "الدولة",
    universityNamePlaceholder: "مثال: جامعة الملك سعود",
    countryPlaceholder: "مثال: المملكة العربية السعودية",
  }
};